### ISSUE TITLE
Disappearing Items

### ISSUE THREAD

**Issue by jreach-dev** [shanemadden/factorio-logistic-cargo-wagon#1]
I love the idea of this mod! Some items disapear when put in the logistic cargo wagons.

Missing:
Repair Packs
Yellow Transport Belts
Walls

Works:
Red Ammo
Wood
Coal
Artillery Shells

Not sure what the issue could be. The items are dropped off but are not in the wagon.

**Comment by shanemadden** [comment]
Oohhh it's the stuff that goes to quickbar. How did I miss testing that?!? I know what's wrong, thanks!

**Comment by shanemadden** [comment]
New version released to fix this, thanks again! Let me know if you're still seeing any issues.

**Comment by jreach-dev** [comment]
I will test out as soon as I get the chance. I am totally for supporting this mod as I see it as one of the major features missing from Factorio :)

**Comment by jreach-dev** [comment]
Works like a charm!
