### ISSUE TITLE
Manual/Automatic Nudge

### ISSUE THREAD

**Issue by jreach-dev** [shanemadden/factorio-logistic-cargo-wagon#2]
Hello! Thanks again for this mod. Another quick feedback here.

When a provide/request i s submitted, if train is on automatic, nothing happens until it is toggled to manual then back to automatic. This is only a minor inconvenience but definitely a way to improve quality of the mod :)

**Comment by shanemadden** [comment]
This should be fixed in 0.16.5 as a side-effect of properly adding LTN support, let me know if there's still any issues!
