### ISSUE TITLE
Feature Request: Run Logistics While Manual

### ISSUE THREAD

**Issue by jreach-dev** [shanemadden/factorio-logistic-cargo-wagon#3]
Hello! 

Would it be possible to make a check box that allows the logistics to work while the train is in manual mode? 

Thanks again!

**Comment by shanemadden** [comment]
That should be doable - it seems like it'd be pretty smooth addition to put a "manual mode" setting in the station list dropdown to configure what the wagon does in manual mode.

**Comment by jreach-dev** [comment]
Changed my mind. I actually find it useful to turn it to manual in case I am flooding my factory storage with ore :P
