### ISSUE TITLE
Tweak Request: Default Request Stack Size

### ISSUE THREAD

**Issue by jreach-dev** [shanemadden/factorio-logistic-cargo-wagon#5]
Hello!

Would it be okay to make the default stack size when clicking request not the entire wagon? I keep accidentally sending all my logistics robots out when I only want one stack in my wagon. I think this is why vanilla requester chests default to a single stack. Just a thought! Feel free to close this if you disagree.

Thanks again!

**Comment by jreach-dev** [comment]
Actually I take this back. I usually use this for grabbing ore. Just a pain when loading up utility wagons.

**Comment by shanemadden** [comment]
Actually I was thinking it might be a good compromise to have it request 40 stacks by default when you're creating a request in the wagons 1st request slot, but then default to 1 stack for the 2nd through last slots, how would that work for you?

**Comment by jreach-dev** [comment]
That sounds great. I will test it out for you :)

**Comment by shanemadden** [comment]
Latest version has this added, should work a little better!
